import { DEMO_NOW, parseRoute, scenarioNames, scenarioView, SYNTHETIC_LABEL } from './model';
import type { Scenario } from '../src/demo/reference-fixtures';
import type { DataProvenance } from '../src/lib/reference-truth/models';

const main = document.querySelector<HTMLElement>('#main')!;
const escape = (v: unknown) => String(v ?? 'Unavailable').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[c]!);
const number = (v: number | null | undefined) => v == null ? 'Unavailable' : v.toLocaleString('en-US', { maximumFractionDigits: 3 });
const timestamp = (v: number | null | undefined) => v == null ? 'Timestamp missing' : new Date(v).toISOString();
const age = (v: number | null | undefined) => v == null ? 'Unknown age' : `${number(v / 1000)} s old`;
const source = (p?: DataProvenance) => p ? `${escape(p.provider.name)}<small>${escape(p.source)} · ${escape(p.mode)}</small>` : 'Unavailable';
const metric = (label: string, value: string, note: string) => `<div class="metric"><dt>${label}</dt><dd>${value}</dd><p>${note}</p></div>`;
function home() {
  const { result: example } = scenarioView('stale-reference');
  return `<section class="hero"><div><p class="eyebrow">THE EVIDENCE LAYER FOR TOKENIZED STOCKS</p><h1>A price difference<br>is only the <em>start.</em></h1><p class="lead">AfterClose helps users determine whether a tokenized-stock price difference is supported by sufficient evidence to proceed to review.</p><div class="actions"><a class="button primary" href="#/lab/stale-reference">Explore the scenario lab <span aria-hidden="true">→</span></a><a class="text-link" href="#/lab/fresh-evidence">See complete fictional evidence</a></div><p class="fine">A reasoning demonstration. No live feeds, wallets, quotes or transaction execution.</p></div><aside class="hero-card"><div class="card-top"><span class="eyebrow">A FICTIONAL CASE</span><span class="pill">12 SCENARIOS</span></div><h2>Fresh token.<br>Stale reference.</h2><div class="signal"><span>Token evidence</span><strong>${age(example.tokenPriceAgeMs)}</strong></div><div class="signal"><span>Underlying evidence</span><strong>${age(example.referenceAgesMs[0])}</strong></div><div class="example-decision"><span class="decision-tag wait">${example.decision}</span><p>A recent observation does not make an old price current.</p></div><a href="#/lab/stale-reference">Inspect the evidence <span aria-hidden="true">↗</span></a></aside></section>
  <section class="workflow"><p class="eyebrow">FROM A DIFFERENCE TO A DEFENSIBLE DECISION</p><h2>Six steps. Every assumption visible.</h2><ol><li><b>01</b><strong>Tokenized stock evidence</strong><span>Identity, price and its own timestamp</span></li><li><b>02</b><strong>Underlying reference evidence</strong><span>Independent sources, separate clocks</span></li><li><b>03</b><strong>Multiplier / session validation</strong><span>Share basis and fictional session inputs</span></li><li><b>04</b><strong>Execution evidence</strong><span>Fictional liquidity and quote checks</span></li><li><b>05</b><strong>Reference Truth Engine</strong><span>The canonical deterministic rules</span></li><li><b>06</b><strong>WAIT / MONITOR / PROCEED_TO_REVIEW</strong><span>Review eligibility; execution stays disabled</span></li></ol></section>
  <section class="tour"><div><p class="eyebrow">A ONE-MINUTE TOUR</p><h2>Change the evidence.<br>Understand the decision.</h2></div><a class="tour-link" href="#/lab/stale-reference"><b>01</b><span>Start with stale evidence<small>Why the engine waits</small></span><span aria-hidden="true">↗</span></a><a class="tour-link" href="#/lab/fresh-evidence"><b>02</b><span>Inspect complete evidence<small>What allows further review</small></span><span aria-hidden="true">↗</span></a><a class="tour-link" href="#/lab/missing-multiplier"><b>03</b><span>Remove multiplier validity<small>How a missing assumption changes the result</small></span><span aria-hidden="true">↗</span></a></section>`;
}
function lab(id: Scenario) {
  const { title, evidence: e, result: r } = scenarioView(id);
  const priceRows = [{ name: 'Token / per token', item: e.tokenPrice, age: r.tokenPriceAgeMs }, ...e.references.map((item, i) => ({ name: 'Independent equity / per share', item, age: r.referenceAgesMs[i] }))];
  const state = r.decision === 'PROCEED_TO_REVIEW' ? 'review' : r.decision === 'WAIT' ? 'wait' : 'monitor';
  const explanation = r.decision === 'WAIT' ? 'Evidence is missing, stale or fails a required check. Resolve the blockers before review.' : r.decision === 'MONITOR' ? 'Evidence supports a comparison, but the configured session or interpretation does not allow review.' : 'The fictional inputs pass the configured checks for further review. This is not a recommendation. Execution remains disabled.';
  return `<section class="lab-heading"><div><p class="eyebrow">SYNTHETIC SCENARIO LAB / 12 CASES</p><h1>Inspect the reasoning.</h1><p>Every company, provider, price, session, multiplier and execution input is fictional.</p></div><div class="clock"><span>FROZEN EVALUATION TIME</span><strong>${timestamp(DEMO_NOW)}</strong><small>Refresh never makes this evidence live.</small></div></section>
  <div class="lab-grid"><aside class="scenario-nav"><label for="scenario-select">Choose a scenario</label><select id="scenario-select">${Object.entries(scenarioNames).map(([key, name]) => `<option value="${key}" ${key === id ? 'selected' : ''}>${escape(name)}</option>`).join('')}</select><nav aria-label="All synthetic scenarios">${Object.entries(scenarioNames).map(([key, name], i) => `<a href="#/lab/${key}" ${key === id ? 'aria-current="page"' : ''}><span>${String(i + 1).padStart(2, '0')}</span>${escape(name)}</a>`).join('')}</nav><p class="fine">Original fixtures. Original engine. All decisions evaluated in your browser.</p></aside><article class="scenario-content"><section class="decision-card ${state}"><p class="eyebrow">${escape(title)}</p><h2 class="decision" data-decision="${r.decision}" aria-live="polite">${r.decision}</h2><p>${explanation}</p><div class="decision-foot"><span>${e.underlying?.company ?? 'Underlying unavailable'}</span><span>EXECUTION DISABLED</span></div></section>
  <section class="evidence-section"><div class="section-title"><h2>Why this decision?</h2><span>${r.findings.length} findings</span></div>${r.findings.length ? `<ul class="findings">${r.findings.map(f => `<li data-code="${f.code}"><span class="finding-label">${f.severity === 'blocking' ? 'BLOCKING' : 'CAUTION'}</span><div><strong>${escape(f.code.replaceAll('_', ' '))}</strong><p>${escape(f.message)}</p></div></li>`).join('')}</ul>` : '<p class="passed">All configured checks passed with synthetic evidence. Proceed to review only.</p>'}</section>
  <section class="evidence-section"><div class="section-title"><h2>Price evidence & provenance</h2><span>FICTIONAL INPUTS</span></div><p class="fine">Price time and observation time are separate. Scroll the table horizontally on small screens.</p><div class="table-scroll" tabindex="0" role="region" aria-label="Price evidence; scroll horizontally"><table><caption>Supplied prices, freshness and sources</caption><thead><tr><th>Evidence</th><th>Price</th><th>Price timestamp / age</th><th>Observed at</th><th>Provenance</th></tr></thead><tbody>${priceRows.map(row => `<tr><th>${row.name}</th><td>${number(row.item?.price)} ${row.item?.currency ?? ''}</td><td>${timestamp(row.item?.priceAt?.unixMs)}<small>${age(row.age)}</small></td><td>${timestamp(row.item?.observedAt?.unixMs)}</td><td>${source(row.item?.provenance)}</td></tr>`).join('')}${e.references.length === 0 ? '<tr><th>Independent references</th><td colspan="4">No independent evidence supplied in this fictional scenario.</td></tr>' : ''}</tbody></table></div></section>
  <section class="evidence-section"><h2>Validation & execution evidence</h2><dl class="metrics">${metric('Shares per token', number(e.multiplier?.sharesPerToken), e.multiplier ? `Fictional validity: ${timestamp(e.multiplier.effectiveAtMs)} → ${timestamp(e.multiplier.validUntilMs)}. Observed ${timestamp(e.multiplier.observedAt?.unixMs)}. ${source(e.multiplier.provenance)}` : 'Multiplier evidence unavailable; validity cannot be assumed.')}${metric('Underlying session', escape(r.session), `Fictional input, not a live market calendar. Observed ${timestamp(e.session?.observedAt?.unixMs)}. ${source(e.session?.provenance)}`)}${metric('Normalized token / share', number(r.normalizedTokenPrice), 'Calculated by the canonical engine.')}${metric('Independent reference median', number(r.referenceConsensusPrice), 'Calculated from the supplied fictional sources.')}${metric('Normalized difference', r.normalizedGapBps == null ? 'Unavailable' : `${number(r.normalizedGapBps)} bps`, 'A difference alone cannot establish review eligibility.')}${metric('Observation age', age(r.observationAgeMs), timestamp(e.observedAt?.unixMs))}${metric('Available liquidity', `${number(e.liquidity?.availableNotional)} ${e.liquidity?.currency ?? ''}`, `Observed ${timestamp(e.liquidity?.observedAt?.unixMs)}. ${source(e.liquidity?.provenance)}`)}${metric('Fictional quote evidence', e.quote ? `${number(e.quote.totalQuoteAmount)} ${e.quote.currency}` : 'Unavailable', e.quote ? `Fictional executable flag: ${e.quote.executable ? 'yes' : 'no'}. Observed ${timestamp(e.quote.observedAt?.unixMs)}. Slippage ${number(e.quote.estimatedSlippageBps)} bps · Expires ${timestamp(e.quote.expiresAtMs)}. ${source(e.quote.provenance)}` : 'No quote evidence supplied.')}${metric('Order quantity', `${number(e.order?.quantityTokens)} tokens`, 'Fictional engine input. No order is submitted.')}${metric('Execution capability', 'DISABLED', 'No wallet, RFQ integration, simulation or transaction capability exists in this preview.')}</dl></section><p class="end-note">${SYNTHETIC_LABEL}<br>Research thresholds are illustrative. No current market condition is asserted.</p></article></div>`;
}
function render(focus = false) {
  try {
    const route = parseRoute(location.hash);
    document.title = route.kind === 'scenario' ? `AfterClose | ${scenarioNames[route.id]} — Synthetic` : 'AfterClose | Synthetic judging preview';
    main.innerHTML = route.kind === 'home' ? home() : route.kind === 'scenario' ? lab(route.id) : '<section class="empty"><p class="eyebrow">SCENARIO NOT FOUND</p><h1>This scenario does not exist.</h1><p>No substitute evidence or decision is shown.</p><a class="button primary" href="#/lab/stale-reference">Return to the synthetic lab</a></section>';
    document.querySelector<HTMLSelectElement>('#scenario-select')?.addEventListener('change', event => { location.hash = `/lab/${(event.target as HTMLSelectElement).value}`; });
  } catch {
    main.innerHTML = '<section class="empty" role="alert"><h1>The demonstration could not be displayed.</h1><p>No substitute evidence or decision is shown. Refresh to retry the static demonstration.</p><a href="#/">Return to overview</a></section>';
  }
  if (focus) { main.focus(); window.scrollTo(0, 0); }
}
window.addEventListener('hashchange', () => { if (location.hash !== '#main') render(true); });
render();
