import Link from "next/link";
import { previewMode } from "@/lib/preview-mode";
import { SyntheticDashboard } from "@/components/synthetic-dashboard";
import { loadCompetition } from "@/lib/competition/load";
import { timestampLabel, ageLabel } from "@/lib/evidence/presentation";
import { RefreshEvidence } from "@/components/refresh-evidence";
import { SnapshotNotice } from "@/components/snapshot-notice";
import { EvidenceReceiptPanel } from "@/components/evidence-receipt";
import { LiveFreshness } from "@/components/live-freshness";
import { BUILD_INFO } from "@/lib/build-info";
import { ENGINE_ID } from "@/lib/competition/receipt";
import { allowedLiveQuery } from "@/lib/binance/request-policy";

export const dynamic = "force-dynamic";
export const runtime = "nodejs";
export function generateMetadata(){return {title:previewMode()==="synthetic"?"AfterClose | Synthetic demo":"AfterClose | Live Evidence"};}
export default async function LiveEvidencePage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}) {
  if (previewMode() === "synthetic") return <SyntheticDashboard />;
  const { current, snapshot, saved } = await loadCompetition(allowedLiveQuery(await searchParams));
  const r = current.receipt, result = r.engine.result, o = r.observation;
  const now = r.evaluatedAtMs;
  return <main id="main-content" className="evidence-dashboard competition-dashboard">
    <header className="nav"><Link className="brand" href="/live">AfterClose<span className="beta">LIVE EVIDENCE</span></Link><Link className="truth-link" href="/demo" prefetch={false}>Scenario Lab · synthetic ↗</Link></header>
    <div className="live-mode-banner">LIVE EVIDENCE MODE · Actual provider observations · No trading</div>
    <section className="dashboard-intro"><div><div className="eyebrow">TOKENIZED STOCKS / TEMPORAL TRUTH</div><h1>NVDAon / NVDA<br /><span>Can the evidence<br />support the gap?</span></h1><p>AfterClose verifies whether a tokenized-stock price difference has enough evidence to proceed to review. Independent NVDA reference: UNAVAILABLE. Dated multiplier and execution evidence are also missing.</p><LiveFreshness key={now} evaluatedAtMs={now} providerAtMs={o.quote?.tokenPriceUpdatedAt ?? null} observedAtMs={r.fields[0].observedAtMs} available={r.fields[0].normalized !== null} connected={o.state === "connected"} /></div><div className="snapshot-note"><a href="#decision" className="decision-summary"><small>AFTERCLOSE DECISION</small><strong data-live-decision>{result.decision}</strong><span>{r.engine.blockerCodes.length} blocking findings · Execution disabled</span></a><p>Evaluated: {timestampLabel(now)}<br />Clocks below are frozen at this evaluation.</p><SnapshotNotice snapshotMs={now} maxAgeMs={30_000} /><RefreshEvidence /><p>Shared provider refresh: at most once per 30 seconds; failures cool down for 60 seconds. Cached evidence keeps its original clocks.</p></div></section>
    {o.state !== "connected" && <section className="connection-notice" role="alert"><h2>LIVE EVIDENCE UNAVAILABLE</h2><p>Current provider data did not validate ({o.failure ?? "unknown"}). No stored or synthetic price replaces it.</p><Link className="truth-link" href="/demo" prefetch={false}>Open Scenario Lab →</Link></section>}
    <section className="workspace" aria-labelledby="token-title"><div className="section-top"><div><div className="eyebrow">01 / TOKENIZED STOCK</div><h2 id="token-title">{r.asset?.symbol ?? "NVDAon — discovery unavailable"}</h2><p>{r.asset?.company ?? "Current company metadata unavailable"}</p></div><span className="network">BSC · CHAIN 56</span></div><div className="connected-panel"><p className="contract">{r.asset?.contract ?? "Current contract unavailable"}</p><p>Issuer: {r.asset?.issuer ?? "Unavailable"} · Decimals: {r.asset?.decimals ?? "Unavailable"} · Historical contract comparison: <strong>{r.discovery}</strong></p>
      {r.discovery !== "MATCH" && <p className="connection-notice">Identity gate blocked. A changed or unverified asset cannot reach PROCEED_TO_REVIEW.</p>}
      <div className="metrics dashboard-metrics"><div><small>Binance Web3 RWA · tokenPrice · USD/token</small><strong data-token-price>{o.quote?.tokenPrice ?? "Unavailable"}</strong><span>Exact provider decimal. Not an equity price.</span></div><div><small>Independent equity reference: UNAVAILABLE</small><strong>Independent NVDA quote unavailable</strong><span>Two independent providers are required by the engine. Token-derived references do not count.</span></div></div>
      <div className="clock-grid"><div><h3>Provider price update time</h3><p>{timestampLabel(o.quote?.tokenPriceUpdatedAt)}</p><small>tokenPriceUpdatedAt · Unix ms: {o.quote?.tokenPriceUpdatedAt ?? "Unavailable"}<br />Provider-data age: {ageLabel(o.quote?.tokenPriceUpdatedAt, now)}</small></div><div><h3>AfterClose received the price response</h3><p>{timestampLabel(r.fields[0].observedAtMs)}</p><small>Observation age: {ageLabel(r.fields[0].observedAtMs, now)} · Request latency: {r.fields[0].latencyMs ?? "Unavailable"} ms<br />Retrieval time is never a market-event timestamp.</small></div></div>
      <details><summary>Token-derived references — separate from independent equity</summary><p>Price endpoint: {o.quote?.referencePrice ?? "Unavailable"} USD/share<br />Underlying-market endpoint: {o.market?.marketData?.referencePrice ?? "Unavailable"} USD/share</p><p>Binance describes these as per-share conversions derived from token prices. Neither supplies an independent equity event timestamp. They are excluded from the engine reference set.</p></details>
    </div></section>
    <section className="truth-panel" aria-labelledby="qualification-title"><div className="eyebrow">02 / WHAT IS STILL UNKNOWN?</div><h2 id="qualification-title">Qualification, not optimism.</h2><div className="cards"><article><span className="card-number">MULTIPLIER</span><h3>Current applicability unverified</h3><p>Ondo reported: {o.issuer.value ?? "Unavailable"} shares/token<br />Binance reported: {o.token?.tokenToShareRatio ?? "Unavailable"}</p><p>Effective date: unavailable<br />Validity interval: unavailable<br />Issuer observed: {timestampLabel(o.issuer.observedAtMs)}</p><p>Normalized token price and gap withheld. The rule is token price ÷ verified shares/token; an undated report is insufficient.</p><a className="truth-link" href={o.issuer.source}>Official Ondo asset ↗</a></article><article><span className="card-number">MARKET SESSION</span><h3>Scheduled ≠ authoritative</h3><p>Scheduled: {r.session.scheduled.session}<br />Calendar event: {r.session.calendarEvent}<br />Authoritative current state: UNKNOWN</p><p>{r.session.scheduled.reason}</p><p>Review: {timestampLabel(r.session.scheduled.observedAtMs)}<br />Raw Binance status: {o.market?.statusInfo?.marketStatus ?? "Unavailable"}</p><a className="truth-link" href={r.session.scheduled.source}>Published Nasdaq calendar ↗</a></article><article><span className="card-number">EXECUTION EVIDENCE</span><h3>Unavailable · read only</h3><p>Quote: UNAVAILABLE<br />Route: unavailable<br />Simulation: NOT RUN<br />Liquidity / impact / slippage: unavailable</p><p>{r.execution.reason}</p></article></div></section>
    <section id="decision" className="truth-panel" aria-labelledby="decision-title"><div className="eyebrow">03 / REFERENCE TRUTH ENGINE</div><h2 id="decision-title">{result.decision} — why?</h2><p>These findings come from the canonical engine applied to admitted provider evidence. Missing inputs remain missing; no BUY/SELL recommendation is made.</p><ul className="truth-findings">{result.findings.map((f,i) => <li key={`${f.code}-${i}`}><code>{f.code} · {f.severity}</code>{f.message}</li>)}</ul></section>
    <section className="truth-panel"><div className="eyebrow">04 / JUDGE-VERIFIABLE PROVENANCE</div><h2>Inspect any important value.</h2><details><summary>Source · provider time · observed · age · derived · used by engine</summary><div className="comparison-table" tabIndex={0} role="region" aria-label="Evidence provenance"><table><caption>Exact raw values and admission at this evaluation</caption><thead><tr><th>Value / source</th><th>Provider time</th><th>Observed / age / latency</th><th>Derivation / engine use</th></tr></thead><tbody>{r.fields.map(f => <tr key={f.id}><th>{f.label}<p>{String(f.raw ?? "Unavailable")}</p><small>{f.provider}<br />{f.source}</small></th><td>{timestampLabel(f.providerAtMs)}<p>{f.providerTimeSemantics}</p><small>Data age: {f.providerDataAgeMs === null ? "Unknown" : `${f.providerDataAgeMs} ms`}</small></td><td>{timestampLabel(f.observedAtMs)}<p>Observation age: {f.observationAgeMs === null ? "Unknown" : `${f.observationAgeMs} ms`}</p><small>Latency: {f.latencyMs === null ? "Not measured" : `${f.latencyMs} ms`}</small></td><td>{f.derived ? "AfterClose derived" : "Provider supplied"}<p>Used by engine: {f.usedByEngine ? "YES" : "NO"}</p><small>{f.classification} · {f.limitation}</small></td></tr>)}</tbody></table></div><p>Freshness, calendar inference, numeric parsing, decision and receipt digest are AfterClose-derived. A response-envelope timestamp dates the response only. The receipt includes each envelope timestamp separately.</p></details>
    <details><summary>Inspect six Binance request results</summary><ul>{o.audits.map(a => <li key={a.endpoint}>{a.endpoint}: HTTP {a.status ?? "unavailable"} · code {a.code ?? "unavailable"} · {a.latencyMs} ms · observed {timestampLabel(a.observedAtMs)} · envelope {timestampLabel(a.responseTimestamp)}</li>)}</ul></details>
    <h3>Evidence Receipt</h3><code className="receipt-digest" data-receipt-digest>{current.digest}</code><EvidenceReceiptPanel canonicalJson={current.canonicalJson} digest={current.digest} /></section>
    <section className="truth-panel" aria-labelledby="snapshot-title"><div className="eyebrow">05 / OUTAGE CONTINUITY</div><h2 id="snapshot-title">Last verified snapshot</h2>{snapshot ? <><p><strong>HISTORICAL · never a current/live substitute.</strong> Verified here means validated provider transport and receipt integrity, not complete investment evidence.</p><p>Capture: {timestampLabel(snapshot.capturedAtMs)} · Age: {snapshot.ageMs === null ? "Unknown" : `${Math.floor(snapshot.ageMs / 1000)} seconds`}<br />Original verdict: {snapshot.envelope.receipt.engine.result.decision} · Original token classification: {snapshot.envelope.receipt.freshness.status}</p><EvidenceReceiptPanel canonicalJson={snapshot.envelope.canonicalJson} digest={snapshot.digest} historical /></> : <p>No validated local snapshot is available. Live failure never produces a synthetic replacement.</p>}<p className="fine">Local persistence only. {saved ? "This evaluation was saved." : "Existing snapshot retained or no eligible snapshot saved."} Storage may be unavailable on ephemeral hosting.</p></section>
    <footer><p className="build-identity">AfterClose Competition Build · Build: {BUILD_INFO.commit.slice(0,12)}{BUILD_INFO.dirty ? " (working tree)" : ""} · Source: {BUILD_INFO.sourceDigest.slice(0,12)}<br />Engine: {ENGINE_ID}</p><Link className="truth-link" href="/demo?scenario=fresh-evidence" prefetch={false}>Open a complete synthetic scenario →</Link><p>Research evidence only. No wallet, signing, trading or transaction broadcasting.</p></footer>
  </main>;
}
